openapi: 3.0.1
info:
  title: .NET Core Web API
  version: v1
  host: api-project-14772174376.appspot.com
paths:
  /api/HealthCheck:
    get:
      tags:
        - HealthCheck
      responses:
        '200':
          description: Success
components: {}
